IrodsHost:
IrodsPort:
IrodsZone:
IrodsAdminUser:
IrodsAdminPassword:
IrodsAdminPasswordFile:
IrodsAdminLoginType:
IrodsAuthScheme:
IrodsNegotiationPolicy: native
IrodsDefaultResource:
OidcUrl:
OidcClientId: irods-go-rest
OidcClientSecret:
OidcClientSecretFile:
OidcRealm:
OidcScope: openid profile email
PublicUrl: http://localhost:8080
RestLogLevel: info
